---
Name: clubmaster
---
# Extend LeftAndMain (Hide Help)
LeftAndMain:
  extensions:
    - CustomLeftAndMain
# Add extension SiteConfig: add folder to store files of type "antraege"
SiteConfig:
  extensions:
    - ClubAdminSiteConfig
# Add extension ModelAdmin: remove delete all checkbox
#ModelAdmin:
#  extensions:
#    - ClubAdminModelAdmin
# Add file extension to allowed extensions
File:
  allowed_extensions:
    - antrag

# Number of displayed items
ClubAdmin:
  items_per_page: 20

