---
Name: clubmaster
---
# Extend LeftAndMain (Hide Help)
LeftAndMain:
  extensions:
    - CustomLeftAndMain
# Add extension SiteConfig: add folder to store files of type "antraege"
SiteConfig:
  extensions:
    - ClubAdminSiteConfig
# Add extension ModelAdmin: remove delete all checkbox
ModelAdmin:
  extensions:
    - ModelAdminExtension
# Add file extension to allowed extensions
File:
  allowed_extensions:
    - antrag

# Enable / Disable Betterbuttons
ClubMember:
  better_buttons_enabled: true
ClubMemberPending:
  better_buttons_enabled: false
ClubMemberType:
  better_buttons_enabled: false

# Number of displayed items
ClubAdmin:
  items_per_page: 20

