---
Name: clubmaster
---
# Extend LeftAndMain (Hide Help)
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SYBEHA\Clubmaster\Extensions\CustomLeftAndMain
# Add extension SiteConfig: add folder to store files of type "antraege"
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - SYBEHA\Clubmaster\Extensions\ClubAdminSiteConfig

# Add file extension to allowed extensions
SilverStripe\Assets\File:
  allowed_extensions:
    - antrag

# Number of displayed items
SYBEHA\Clubmaster\Admins\ClubAdmin:
  items_per_page: 25
  extensions:
    - ClubAdminImport

# Betterbuttons (unclecheese/silverstripe-gridfield-betterbuttons)
ClubMemberPending:
  better_buttons_enabled: false
