---
Name: clubmaster
---
# Extend LeftAndMain (Hide Help)
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SYBEHA\Clubmaster\Extensions\ClubAdminLeftAndMain

# Add extension SiteConfig: add folder to store files of type "antraege"
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - SYBEHA\Clubmaster\Extensions\ClubAdminSiteConfig

# Add file extension to allowed extensions
SilverStripe\Assets\File:
  file_types:
    antrag: 'Jimev Antrag'
  allowed_extensions:
    - antrag

# Number of displayed items
SYBEHA\Clubmaster\Admins\ClubAdmin:
  page_length: 25
  extensions:
    - SYBEHA\Clubmaster\Extensions\ClubAdminImport

# Requirements
---
After:
    - 'assetsimage'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'lhasselb/clubmaster: client/dist/styles/main.css'
  extra_requirements_javascript:
    - 'lhasselb/clubmaster: client/dist/js/main.js'

# DO NOT FORGET TO CONFIGURE MAIL
#Example:
#SilverStripe\Control\Email\Email:
#  admin_email:
#    info@jimev.de: 'JIM e.V.'
