---
Name: clubmaster
---
# Extend LeftAndMain (Hide Help)
LeftAndMain:
  extensions:
    - CustomLeftAndMain
# Add extension to allowed extensions
File:
  allowed_extensions:
    - antrag

ClubMember:
  better_buttons_enabled: true

ClubMemberPending:
  better_buttons_enabled: false

ClubMemberType:
  better_buttons_enabled: false

SiteConfig:
  extensions:
    - ClubAdminSiteConfig

