---
Name: clubmaster
---
# ===================
# Extend LeftAndMain
# ===================
SilverStripe\Admin\LeftAndMain:
  extensions:
# (Hide Help)
    - Sybeha\Clubmaster\Extensions\ClubAdminLeftAndMain
  extra_requirements_css:
    - 'lhasselb/clubmaster: client/dist/styles/bundle.css'
  extra_requirements_javascript:
      - 'lhasselb/clubmaster: client/dist/js/bundle.js'
# ===================
# Extend SiteConfig
# ===================
Silverstripe\SiteConfig\SiteConfig:
  extensions:
# Add folder to store files of type "antraege"
    - Sybeha\Clubmaster\Extensions\ClubAdminSiteConfig
# ===================
# Extend File
# ===================
SilverStripe\Assets\File:
  allowed_extensions:
# Add file extension to allowed extensions
    - antrag
# ===================
# Extend ClubAdmin
# ===================
Sybeha\Clubmaster\Admins\ClubAdmin:
# Number of displayed items
  page_length: 25
  extensions:
    - Sybeha\Clubmaster\Extensions\ClubAdminImport
# ===================
# Extend ClubMember
# ===================
