---
Name: clubmaster
---
# Extend LeftAndMain (Hide Help)
LeftAndMain:
  extensions:
    - CustomLeftAndMain
# Add extension SiteConfig: add folder to store files of type "antraege"
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - ClubAdminSiteConfig

# Add file extension to allowed extensions
SilverStripe\Assets\File:
  allowed_extensions:
    - antrag

# Number of displayed items
ClubAdmin:
  items_per_page: 25
  extensions:
    - ClubAdminImport

# Betterbuttons (unclecheese/silverstripe-gridfield-betterbuttons)
ClubMemberPending:
  better_buttons_enabled: false
